### PR TITLE
Delete event-listener-html-clickable.html

### PR DESCRIPTION
**Pull request by cvrebert**
Turns out no clickability hacks are necessary for this, based on testing with iOS 9.1.

### CODE REVIEW

**Comment by cvrebert** [comment]
@patrickhlauke Ping?

**Comment by patrickhlauke** [comment]
you know, i can't actually remember anymore what i did or didn't test at the time / which iOS version needed it...but yup in recent versions it's unnecessary. cheers!

**Comment by cvrebert** [comment]
I was the one who added this file, in order to be able to easily test whether the hacks made any difference in the first place. :smile:

**Comment by patrickhlauke** [comment]
hah :)

**Pull request merged**
